version: "3"
services:
  php:
    build: docker/php
    volumes:
      - .:/app:cached
    working_dir: /app
    container_name: framey_php

  nginx:
    image: nginx:1.15.0
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    volumes:
      - .:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: framey_nginx

  mysql:
    image: mysql:8.0.27
    container_name: framey_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1:${MYSQL_PORT}:3306
